### ISSUE TITLE
Desktop build

### ISSUE THREAD

**Issue by johannphilippe** [BertrandBev/code_field#1]
I could build the example for Linux target by removing the dependency to keyboard_visibility. 
It involved to remove the package dependency in pubspec.yaml, and to comment / remove lines 7, 115-116, 129-130 in code_field.dart.

I don't know how much the keyboard_visibility is necessary on mobile platforms, but it would be great to find a way to  have a fully cross platform package for this project. 

If this dependency is necessary, maybe we could find another way to achieve it without dependency, just by handwritten code (I think I already made something like that in an app). 

What do you think about that ?

**Comment by BertrandBev** [comment]
You're right, we should get rid of it. I'll take a look at it!

**Comment by BertrandBev** [comment]
Ok, I just got rid of that dependency, it should work better now!

**Comment by johannphilippe** [comment]
Great, thanks. 

I could build an example with the last version. 

Just had to change the `buildTextSpan` signature so that it matches this migration guide : https://flutter.cn/docs/release/breaking-changes/buildtextspan-buildcontext in the following files : 
- code_field.dart line 10
- code_controller.dart line 210

```
TextSpan buildTextSpan({required BuildContext context, TextStyle? style, bool? withComposing})
{
...
}
```

**Comment by BertrandBev** [comment]
Right that's because of [the breaking change introduced in 2.2](https://flutter.dev/docs/release/breaking-changes/buildtextspan-buildcontext). I'll merge the fix in the beta branch
