### ISSUE TITLE
Bug: colors changed in web when cursor is set

### ISSUE THREAD

**Issue by 4ntoine** [BertrandBev/code_field#11]
There is some bug in the live demo: i can scroll down and see the correctly highlighted area:
<img width="946" alt="Снимок экрана 2021-07-23 в 17 59 21" src="https://user-images.githubusercontent.com/846671/126785294-4132bd17-9bd8-4fb0-bc5b-e3c80f407eeb.png">

However if i set the cursor the colors are changed:
<img width="939" alt="Снимок экрана 2021-07-23 в 17 59 28" src="https://user-images.githubusercontent.com/846671/126785315-de3e2a86-eff5-4d89-b0b4-71eec7c4582c.png">

See "moveTo" color is changed.

It happens not in all the themes.
Let me know if you can reproduce it or i will provide more details on this.

**Comment by 4ntoine** [comment]
Same here ("main" color is changed):
before
<img width="964" alt="Снимок экрана 2021-07-23 в 17 59 04" src="https://user-images.githubusercontent.com/846671/126785502-d4fe2e0b-6351-43d6-b0d4-c02a9f1588c2.png">

after cursor is set:
<img width="944" alt="Снимок экрана 2021-07-23 в 17 59 13" src="https://user-images.githubusercontent.com/846671/126785510-e575a1eb-6909-4460-ae76-aeb3b840a92f.png">

**Comment by 4ntoine** [comment]
"Javascript + vs" completely looses all the colors!
<img width="970" alt="Снимок экрана 2021-07-23 в 18 04 11" src="https://user-images.githubusercontent.com/846671/126785624-cdead834-6a8c-4cf6-bda0-34f64b71dff7.png">
<img width="934" alt="Снимок экрана 2021-07-23 в 18 04 20" src="https://user-images.githubusercontent.com/846671/126785653-662d9f9f-cf4b-4aca-94d2-9dd1459a3f20.png">

**Comment by BertrandBev** [comment]
Ah, good catch, it was caused by the `webSpaceFix` flag (introduced to address [this issue]( https://github.com/flutter/flutter/issues/77929))
I fixed it in 1.0.1-2
