### ISSUE TITLE
Add more control methods to controller

### ISSUE THREAD

**Issue by johannphilippe** [BertrandBev/code_field#13]
Hello, 
I'm connecting the Code text field to a virtual keyboard (provided here : https://pub.dev/packages/new_virtual_keyboard/install)
It works fine calling the `insertStr` of the controller to insert characters. 
But, if I receive a backspace from virtual keyboard, I would need to have a method to remove a character, or selection.
Thanks for your work

**Comment by johannphilippe** [comment]
I tried with this method in the controller, it works fine. 
``` dart
  void removeCharOrSelection()
  {
    final sel = selection;
    if(sel.start == sel.end) {
      if(sel.start > 0)  {
        text = text.replaceRange(sel.start - 1, sel.end, "");
        selection = sel.copyWith(
          baseOffset: sel.start - 1,
          extentOffset: sel.start - 1,
        );
      }
    } else {
      text = text.replaceRange(selection.start, selection.end, "");
      selection = sel.copyWith(
        baseOffset: sel.start,
        extentOffset: sel.start,
      );
    }
  
```

**Comment by BertrandBev** [comment]
Sure, I added those in `65695ca2`
