### ISSUE TITLE
CodeField read only

### ISSUE THREAD

**Issue by Mythar** [BertrandBev/code_field#14]
Very nice editor!
Would be nice to have a readOnly option in the CodeField and a onTextChanged callback.

**Comment by BertrandBev** [comment]
I added an `enabled` flag in `b58f58c6`, and `onChanged` callback `b897bcbb8`

**Comment by leoshusar** [comment]
Would be nice to have the actual `readOnly` option, because `enabled: false` does not let you select the text. Using `readOnly` the text is still selectable.
