### ISSUE TITLE
[Bug] Line numbers over 999 wrap

### ISSUE THREAD

**Issue by SergeShkurko** [BertrandBev/code_field#20]
I opened demo https://bertrandbev.github.io/code_field
and tried copy-paste code for test performance 

When i puted over 999 code lines i received bug with line numbers wrap

![image](https://user-images.githubusercontent.com/18213789/137261236-fa4c41e3-4693-4171-813c-55666e5a4d5f.png)

**Comment by BertrandBev** [comment]
Ah indeed. I'll look into it!

**Comment by BertrandBev** [comment]
So for now you have the  `LineNumberStyle.width` configuration available! Crank it up and it'll leave more space for line numbers
