### ISSUE TITLE
Line numbers wrap when >999 lines

### ISSUE THREAD

**Issue by Apokalypser** [BertrandBev/code_field#32]
Experienced in live demo when editing a file with more than 999 lines.

<img width="971" alt="Bildschirmfoto 2022-04-07 um 21 57 03" src="https://user-images.githubusercontent.com/2430749/162285758-9cab3cae-1be8-4c5c-b6cd-51fccea8c773.png">

**Comment by rickwyz** [comment]
LineNumberStyle lineNumberStyle = LineNumberStyle(width: 75, textAlign: TextAlign.center);

return Scaffold(
  appBar: AppBar(title: Text(config.key)),
  body: SingleChildScrollView(
    child: CodeField(
      controller: _codeController!,
      textStyle: TextStyle(fontFamily: 'SourceCode'),
      lineNumberStyle: lineNumberStyle,
    ),
),

Just increase the LineNumberStyle.width
