### ISSUE TITLE
TextField shrinks to one line on click

### ISSUE THREAD

**Issue by alexeyinkin** [BertrandBev/code_field#45]
There is a bug with current `master`.

1. Run the example from this package in Chrome. The window shows as usual:
![image](https://user-images.githubusercontent.com/44893228/174071531-eee988a5-d7c2-4580-9688-b331c76556f8.png)

2. Click inside the text field. The field shrinks to one line:
![image](https://user-images.githubusercontent.com/44893228/174071780-d7b4625c-c303-4756-9815-edd25e8f30a5.png)

This is not happening with v1.0.2.

I nailed it down to this line:
https://github.com/BertrandBev/code_field/blob/befb10f12db622400c86ca388edc67c91b550774/lib/src/code_field.dart#L278
Comment it out, and it works as before.

The change was introduced in https://github.com/BertrandBev/code_field/pull/36/files
@ihorkozar what was the motivation for it?

**Comment by alexeyinkin** [comment]
On Android, the effect of this line is to show a keyboard with missing "new line" button and "Done" button instead:
![Screenshot_20220618-122538](https://user-images.githubusercontent.com/44893228/174429663-df6f2c34-31de-4195-9e2c-0cb9b819d56b.jpg)

"New line" button re-appears if this line is commented out.

I understand this was added in an attempt to disable suggestions as per this answer: https://stackoverflow.com/a/61537289/11382675

If on some devices a keyboard shows suggestions, I would like to see a separate issue in which an investigation could be done.

Until then I suggest removing this line.

Tested with Flutter 3.0.2 on SM T585 tablet with Android 8.1.0.

**Comment by ihorkozar** [comment]
@alexeyinkin There was a problem with the constantly burning spell checker in Firefox. It is worth making this an optional parameter. Perhaps you see another solution to the spell check problem ?

**Comment by alexeyinkin** [comment]
I have not yet looked into it.
We are testing this editor in quite a significant project: https://play.beam.apache.org
If we stick to this editor, this issue will get on our radar eventually.

If you investigated it, please create a separate issue to continue there with information on browsers affected, screenshots etc.

**Comment by layerzzzio** [comment]
hey @alexeyinkin I tried https://play.beam.apache.org/
It's pretty neat!! congrats on the result
did you use code_field (code_text_field  in pub dev) in the end?

**Comment by alexeyinkin** [comment]
The currently deployed version uses the `master` branch and not a version published on pub.dev
