### ISSUE TITLE
Delete CodeController.onChange

### ISSUE THREAD

**Issue by alexeyinkin** [BertrandBev/code_field#65]
`CodeController.onChange` can be replaced with

```dart
controller.addListener(() {
  final text = controller.rawText;
});
```

If we delete `onChange()`, the benefits are:
- User code is less messy. If they use both ways to listen to changes, their code is hard to maintain.
- Less code for us to maintain.
- Following Flutter convention. Controllers are listened to, and widgets have `onChanged` because they are disposable and so cannot be listened to. Both `TextField` and `CodeField` have one.
- More consistent API. `CodeField.onChanged` is called with dots with webSpaceFix while `CodeController.onChange` is called with spaces.

@BertrandBev still you added `onChange` after `rawText`, so I wander what was the motivation for it. Are you OK with deleting it in the next breaking release?

**Comment by BertrandBev** [comment]
Yes, it makes total sense!
