### ISSUE TITLE
Enable Selection for disabled Textfield

### ISSUE THREAD

**Issue by S-Man42** [BertrandBev/code_field#68]
Hi, 

I am using the CodeField mainly for displaying code, rather then writing it. So mainly I have it "enabled = false". Nonetheless I'd like to select some code snippets here and there, but as I see, the selection is only possible on enabled/writeable Textfields.

Is this possible?

Thanks in advance,
Mark

**Comment by mack-at-pieces** [comment]
@S-Man42 readOnly is the property you're looking for.

Mark enabled:true and readOnly: true and you should be good to go!

**Comment by S-Man42** [comment]
Hi,

When using the last stable version 1.0.2, there is no `readOnly`...
So, I need to use the Git repo directly? Are there any plans for a stable release? Can it be used within a productive project?

Next question:
I need to modify the selection controls. Normal `TextFormField` and `SelectableText` have a hook `selectionControls` for it. Is there anything similar in `CodeField` (the idea is, that I need to do something with a copied text directly)

**Comment by gumbarros** [comment]
> Hi,
> 
> When using the last stable version 1.0.2, there is no `readOnly`... So, I need to use the Git repo directly? Are there any plans for a stable release? Can it be used within a productive project?
> 
> Next question: I need to modify the selection controls. Normal `TextFormField` and `SelectableText` have a hook `selectionControls` for it. Is there anything similar in `CodeField` (the idea is, that I need to do something with a copied text directly)

Hey @S-Man42 , reference the package on pubspec the package like [this](https://github.com/BertrandBev/code_field/issues/67#issuecomment-1280822758) while @BertrandBev  don't publish the package.

**Comment by S-Man42** [comment]
Yes, I did this. However it feels not good to do so in a ready for launch project, that's why I asked for stability. Which commit it preferred and can be used for it? The one you mentioned or simething later?

**Comment by gumbarros** [comment]
> Yes, I did this. However it feels not good to do so in a ready for launch project, that's why I asked for stability. Which commit it preferred and can be used for it? The one you mentioned or simething later?

Yes I agree it's better a pub.dev version. I used the lastest commit from this repo.

**Comment by S-Man42** [comment]
> Next question: I need to modify the selection controls. Normal `TextFormField` and `SelectableText` have a hook `selectionControls` for it. Is there anything similar in `CodeField` (the idea is, that I need to do something with a copied text directly)

Can you say something to this one?

**Comment by gumbarros** [comment]
> > Next question: I need to modify the selection controls. Normal `TextFormField` and `SelectableText` have a hook `selectionControls` for it. Is there anything similar in `CodeField` (the idea is, that I need to do something with a copied text directly)
> 
> Can you say something to this one?

Created https://github.com/BertrandBev/code_field/pull/69
