### ISSUE TITLE
README Update for theme and CodeTheme

### ISSUE THREAD

**Issue by semperos** [BertrandBev/code_field#71]
Thanks for your open source contributions!

The README still shows usage of the once-deprecated and now-deleted `theme` argument for `CodeController`, where now a wrapping `CodeTheme` with `CodeThemeData` are needed.

Thanks for updating the executable examples, that made it straightforward to find a working usage.

**Comment by dhust** [comment]
It's not clear how to implement `CodeTheme` or `CodeThemeData`. It would be great if someone could provide an example please :)
