### ISSUE TITLE
"theme" not usable in CodeController

### ISSUE THREAD

**Issue by CodingSmiles** [BertrandBev/code_field#77]
I am not able to use the CodeController's option to add a theme. Here is my issue
![image](https://github.com/BertrandBev/code_field/assets/95686935/5e8dc227-63cb-428b-82cc-efba55bae213)
My error message: The named parameter 'theme' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'theme'.

**Comment by gitsunmin** [comment]
@CodingSmiles  Is there a solution to this error?

**Comment by CodingSmiles** [comment]
I can't see this comment on Github, so I'm replying with an email.
Unfortunately, I don't know any solutions to the error. There must be
something but I'm definitely not the right person to ask this to. I left
that project months ago now 😅

**Comment by CodingSmiles** [comment]
Replying to myself here, I did a little bit of work and made it work

[image: image.png]

Sorry if I'm doing it wrong or nobody asked about this.

**Comment by dhust** [comment]
> Replying to myself here, I did a little bit of work and made it work
> [image: image.png]
> Sorry if I'm doing it wrong or nobody asked about this.

Your image isn't showing. How did you get themes to work?

**Comment by dhust** [comment]
So instead of returning a `CodeField`:
```
return CodeField(
    controller: _codeController!,
    textStyle: TextStyle(fontFamily: 'SourceCode'),

  );
```

We need to return a `CodeTheme` with the `CodeField `as a child:
```
return CodeTheme(
    data: const CodeThemeData(styles: monokaiSublimeTheme),
    child: CodeField(
      controller: _codeController!,
      textStyle: const TextStyle(fontFamily: 'SourceCode'),
    ),
  );
```
