### ISSUE TITLE
FormatException: Nothing to repeat 

### ISSUE THREAD

**Issue by t-m-z** [BertrandBev/code_field#78]
I try to implement a Befunge-Interpreter. Hence I defined a Map<String, TextStyle> BEFUNGE_SYNTAX for the relevant syntax-Highlighting.
The following code causes the FormatException:
 void initState() {
    super.initState();
    _befungeGenerateController = TextEditingController(text: _currentGenerate);
    _befungeInterpretCodeController = CodeController(
      text: _currentInterpret,
      stringMap: BEFUNGE_SYNTAX,
    );
    _inputController = TextEditingController(text: _currentInput);
    _codeGenerateController = TextEditingController(text: _sourceCodeGenerated);
  }

**Comment by BertrandBev** [comment]
Hi! I think that question would better be answered over at https://pub.dev/packages/flutter_highlight!

**Comment by t-m-z** [comment]
Hi, thank you for your answer. I apologize for my little knowledge. 
Your hint leads to another question.
When starting to raise an issue I saw a note (https://github.com/git-touch/highlight.dart/issues/47), that this project seems abandoned, so [we ](https://github.com/alexeyinkin) forked it. The new package is published as: 
https://pub.dev/packages/highlighting
https://pub.dev/packages/flutter_highlighting

Could you have a look at this. Maybe this new fork also solves my problem when using your package.
