### ISSUE TITLE
CodeController theme?

### ISSUE THREAD

**Issue by jarrodcolburn** [BertrandBev/code_field#85]
all the examples have a `theme` property in `CodeController`

```dart
CodeController(
      text: source,
      language: dart,
      theme: monokaiSublimeTheme, // here
    );
```

but I'm not seeing this in the [class definition](https://pub.dev/documentation/code_text_field/latest/code_text_field/CodeController-class.html)

Has it been moved?

**Comment by ghost** [comment]
@jarrodcolburn 

It seems that the style/theme has been moved out of the controller and now it's only a UI thing. I've found an example of a different project that uses the same package and works well for me:
```dart
@override
Widget build(BuildContext context) {
  return Expanded(
    child: CodeTheme(
      data: const CodeThemeData(styles: monokaiSublimeTheme),
      child: CodeField(
        controller: _codeController!,
        textStyle: const TextStyle(
          fontFamily: 'SourceCode',
        ),
      ),
    ),
  );
}
```

Hope it helps!

Cheers,
Antonio Jesus
