### ISSUE TITLE
CodeController copywith method

### ISSUE THREAD

**Issue by ahmet-ozberk** [BertrandBev/code_field#92]
I need the copyWith method in CodeController to update the patternMap variable, can you add it?

**Comment by BertrandBev** [comment]
Can you submit a PR ?

**Comment by ahmet-ozberk** [comment]
I send it

**Comment by BertrandBev** [comment]
Thanks !

**Comment by ahmet-ozberk** [comment]
The error that the patternMap variable is not updated is not resolved with the copyWith method. The source of the error is line 86: patternList.addAll(patternMap!.keys.map((e) => r'($e)')); the patternMap variable could not be updated because r'($e)' was written as '($e)' in this line. The error has been fixed and a new pull request has been sent. Thank you.
